# vim: ft=yaml
language: bash

sudo: required

services: docker

env:
  - TRAVIS_BASH_VERSION="4.1" TRAVIS_GIT_VERSION="1.8.0"

before_install:
  - docker pull koalaman/shellcheck

install:
  - PATH=$PWD/bin:$PATH

script:
  - git --version
  - bash --version
  - make clean install build
  - docker run -it --workdir / --rm -v $(pwd)/src:/src koalaman/shellcheck src/**/*.sh

