# vim: ft=yaml
language: bash

os:
  - linux
  - osx

sudo: required

services: docker

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; brew install gawk; fi

install:
  - export DOCKER_RUN="docker run -it --workdir /scripts --rm -v $(pwd):/scripts"
  - export STYLECHECK_FILES="src/*.sh test/*.sh test/unit-tests/*.sh test/utils/*.sh utils/*.sh"
  - export UNIT_TEST="apk add --no-cache ncurses; test/testunits.sh"

script:
  - git --version
  - bash --version
  - make clean build
  - if [[ "$TRAVIS_OS_NAME" == "linux"  ]]; then $DOCKER_RUN koalaman/shellcheck -x $STYLECHECK_FILES; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"  ]]; then $DOCKER_RUN bash:4.4 bash -c "$UNIT_TEST"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"  ]]; then $DOCKER_RUN bash:3.1 bash -c "$UNIT_TEST"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then make test; fi

