# vim: ft=yaml
language: bash

sudo: required

services: docker

install:
  - shopt -s globstar

script:
  - git --version
  - bash --version
  - make clean build
  - docker run -it --workdir /scripts --rm -v $(pwd):/scripts koalaman/shellcheck -x src/**/*.sh test/**/*.sh utils/**/*.sh
  - docker run -it --workdir /scripts --rm -v $(pwd):/scripts bash:4.4 bash -c 'apk add --no-cache ncurses; test/testunits.sh'
  - docker run -it --workdir /scripts --rm -v $(pwd):/scripts bash:3.1 bash -c 'apk add --no-cache ncurses; test/testunits.sh'

